apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis1
spec:
  selector:
    matchLabels:
      app: redis1
  template:
    metadata:
      labels:
        app: redis1
    spec:
      containers:
        - name: redis1
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_9493aa4f0021
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/redis
      volumes:
        - name: config-volume
          configMap:
            name: redis1-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: redis1
spec:
  selector:
    app: redis1
  ports:
    - port: 6379
      targetPort: 6379